set(headers ${headers}
	extern/NVSE/common/IArchive.h
	extern/NVSE/common/IBufferStream.h
	extern/NVSE/common/IConsole.h
	extern/NVSE/common/ICriticalSection.h
	extern/NVSE/common/IDataStream.h
	extern/NVSE/common/IDatabase.h
	extern/NVSE/common/IDebugLog.h
	extern/NVSE/common/IDirectoryIterator.h
	extern/NVSE/common/IDynamicCreate.h
	extern/NVSE/common/IErrors.h
	extern/NVSE/common/IEvent.h
	extern/NVSE/common/IFIFO.h
	extern/NVSE/common/IFileStream.h
	extern/NVSE/common/IInterlockedLong.h
	extern/NVSE/common/ILinkedList.h
	extern/NVSE/common/IMemPool.h
	extern/NVSE/common/IMutex.h
	extern/NVSE/common/IObjectPool.h
	extern/NVSE/common/IPipeClient.h
	extern/NVSE/common/IPipeServer.h
	extern/NVSE/common/IPrefix.h
	extern/NVSE/common/IRangeMap.h
	extern/NVSE/common/IReadWriteLock.h
	extern/NVSE/common/ISegmentStream.h
	extern/NVSE/common/ISingleton.h
	extern/NVSE/common/ITextParser.h
	extern/NVSE/common/IThread.h
	extern/NVSE/common/ITimer.h
	extern/NVSE/common/ITypes.h
	src/ConditionalData.h
	src/Defs.h
	src/Hooks.h
	src/Manager.h
	src/ObjectProperties.h
	src/PCH.h
	src/RNG.h
	src/SwapData.h
	src/Util.h
)
