set(sources ${sources}
	extern/NVSE/common/IArchive.cpp
	extern/NVSE/common/IBufferStream.cpp
	extern/NVSE/common/IConsole.cpp
	extern/NVSE/common/IDataStream.cpp
	extern/NVSE/common/IDatabase.cpp
	extern/NVSE/common/IDebugLog.cpp
	extern/NVSE/common/IDirectoryIterator.cpp
	extern/NVSE/common/IDynamicCreate.cpp
	extern/NVSE/common/IErrors.cpp
	extern/NVSE/common/IEvent.cpp
	extern/NVSE/common/IFIFO.cpp
	extern/NVSE/common/IFileStream.cpp
	extern/NVSE/common/IInterlockedLong.cpp
	extern/NVSE/common/IMemPool.cpp
	extern/NVSE/common/IMutex.cpp
	extern/NVSE/common/IObjectPool.cpp
	extern/NVSE/common/IPipeClient.cpp
	extern/NVSE/common/IPipeServer.cpp
	extern/NVSE/common/IPrefix.cpp
	extern/NVSE/common/IRangeMap.cpp
	extern/NVSE/common/IReadWriteLock.cpp
	extern/NVSE/common/ISegmentStream.cpp
	extern/NVSE/common/ISingleton.cpp
	extern/NVSE/common/ITextParser.cpp
	extern/NVSE/common/IThread.cpp
	extern/NVSE/common/ITimer.cpp
	extern/NVSE/common/ITypes.cpp
	src/ConditionalData.cpp
	src/Hooks.cpp
	src/Manager.cpp
	src/ObjectProperties.cpp
	src/PCH.cpp
	src/RNG.cpp
	src/SwapData.cpp
	src/Util.cpp
)
